# Generated by Django 4.2.3 on 2023-07-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('imageItem', models.ImageField(upload_to='')),
                ('countItem', models.IntegerField()),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventorization.departments')),
            ],
        ),
    ]
